services:
  # --- BASE DE DONNÉES ---

  db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/seed_exercises.sql:/docker-entrypoint-initdb.d/01_seed_exercises.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  # --- BACKEND (API) ---
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    volumes:
      - ./backend:/home/appuser/backend
    depends_on:
      db:
        condition: service_started
    networks:
      - reseau-web # Pour être accessible par le Proxy (api.jymbro.fr)
      - default # Pour parler à la DB

  # --- FRONTEND (Site Web) ---
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: thomascml/gym-app-frontend
    container_name: gym_frontend
    depends_on:
      backend:
        condition: service_started
    networks:
      - reseau-web # Pour être accessible par le Proxy (jymbro.fr)
      - default

  # --- CACHE ---
  redis:
    image: redis:7-alpine
    container_name: gym_redis
    restart: always
    # Pas de ports : on le garde privé dans le réseau Docker
    networks:
      - default # Pour parler au backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  reseau-web:
    external: true
