version: "3.8"

services:
  # --- LE REVERSE PROXY (Gère le SSL et l'entrée) ---
  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80" # Entrée HTTP publique
      - "443:443" # Entrée HTTPS publique
      - "81:81" # Interface d'administration
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

  # --- BASE DE DONNEES ---
  db:
    image: postgres:16-alpine
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- BACKEND (API) ---
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env.prod
    volumes:
      - ./backend:/home/appuser/backend
    depends_on:
      db:
        condition: service_started

  # --- FRONTEND (Site Web) ---
  frontend:
    build: ./frontend
    image: thomascml/gym-app-frontend
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data:
    driver: local
