version: "3.8"

services:
  # --- SUPPRIME TOUT LE BLOC 'nginx-proxy' ---

  db:
    image: postgres:16-alpine
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    env_file:
      - ./.env.prod
    volumes:
      - ./backend:/home/appuser/backend
    depends_on:
      db:
        condition: service_started
    networks: # AJOUT IMPORTANT
      - reseau-web # Pour que le proxy le trouve
      - default

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "https://api.ton-domaine-gym.com"
    image: thomascml/gym-app-frontend
    container_name: gym_frontend
    depends_on:
      backend:
        condition: service_started
    networks: # AJOUT IMPORTANT
      - reseau-web # Pour que le proxy le trouve
      - default

volumes:
  postgres_data:
    driver: local

networks:
  reseau-web:
    external: true
